"""message

Revision ID: 11503b5f56e4
Revises: 3250395397a0
Create Date: 2024-10-03 01:09:21.226677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11503b5f56e4'
down_revision = '3250395397a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_categories_category', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_recipe_categories_category', 'category', ['categories'], ['id'])

    # ### end Alembic commands ###
